# Generated by Django 5.1.6 on 2025-02-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_category_slug_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
